mbg_websites/urls.py
# -*- coding: utf-8 -*-
"""
mbg_websites URL Configuration.

The 'urlpatterns' list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from mbg_websites import views


urlpatterns = [
    url(r'^$',
        views.start_page,
        name='start-page'),
    url(r'^about/$',
        views.about_page,
        name='about-page'),
    url(r'^help/$',
        views.help_page,
        name='help-page'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^people/', include('people.urls', namespace='people')),
    url(r'^planners/', include('planners.urls', namespace='planners')),
    url(r'^songs/', include('songs.urls', namespace='songs')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    # url(r'^.well-known/acme-challenge/.../$',
    #     views.certificate_challenge),
]

songs/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from songs import views, views_authors, views_songbooks, views_styles, views_files


urlpatterns_authors = [
    url(r'^$',
        views_authors.authors_list,
        name='authors-list'),
    url(r'^deleted/$',
        views_authors.authors_list_deleted,
        name='authors-list-deleted'),
    url(r'^create/$',
        views_authors.authors_create,
        name='authors-create'),
    url(r'^(?P<author_id>\d+)/$',
        views_authors.authors_read,
        name='authors-read'),
    url(r'^(?P<author_id>\d+)/update/$',
        views_authors.authors_update,
        name='authors-update'),
    url(r'^(?P<author_id>\d+)/delete/$',
        views_authors.authors_delete,
        name='authors-delete'),
    url(r'^(?P<author_id>\d+)/delete/undo/$',
        views_authors.authors_delete_undo,
        name='authors-delete-undo'),
    url(r'^(?P<author_id>\d+)/history/$',
        views_authors.authors_history,
        name='authors-history'),
]


urlpatterns_songbooks = [
    url(r'^$',
        views_songbooks.songbooks_list,
        name='songbooks-list'),
    url(r'^deleted/$',
        views_songbooks.songbooks_list_deleted,
        name='songbooks-list-deleted'),
    url(r'^create/$',
        views_songbooks.songbooks_create,
        name='songbooks-create'),
    url(r'^(?P<songbook_id>\d+)/$',
        views_songbooks.songbooks_read,
        name='songbooks-read'),
    url(r'^(?P<songbook_id>\d+)/update/$',
        views_songbooks.songbooks_update,
        name='songbooks-update'),
    url(r'^(?P<songbook_id>\d+)/delete/$',
        views_songbooks.songbooks_delete,
        name='songbooks-delete'),
    url(r'^(?P<songbook_id>\d+)/delete/undo/$',
        views_songbooks.songbooks_delete_undo,
        name='songbooks-delete-undo'),
    url(r'^(?P<songbook_id>\d+)/history/$',
        views_songbooks.songbooks_history,
        name='songbooks-history'),
]


urlpatterns_styles = [
    url(r'^$',
        views_styles.styles_list,
        name='styles-list'),
    url(r'^create/$',
        views_styles.styles_create,
        name='styles-create'),
    url(r'^(?P<style_id>\d+)/$',
        views_styles.styles_read,
        name='styles-read'),
    url(r'^(?P<style_id>\d+)/update/$',
        views_styles.styles_update,
        name='styles-update'),
    url(r'^(?P<style_id>\d+)/delete/$',
        views_styles.styles_delete,
        name='styles-delete'),
]


urlpatterns_files = [
    url(r'^$',
        views_files.files_list,
        name='files-list'),
    url(r'^zip/$',
        views_files.files_download_zip,
        name='files-download-zip'),
    url(r'^zip/all-pptx/$',
        views_files.files_download_zip_pptx,
        name='files-download-zip-pptx'),
    url(r'^zip/all-xml/$',
        views_files.files_download_zip_xml,
        name='files-download-zip-xml'),
]


urlpatterns = [
    url(r'^$',
        views.songs_list,
        name='songs-list'),
    url(r'^deleted/$',
        views.songs_list_deleted,
        name='songs-list-deleted'),
    url(r'^authors/',
        include(urlpatterns_authors)),
    url(r'^songbooks/',
        include(urlpatterns_songbooks)),
    url(r'^styles/',
        include(urlpatterns_styles)),
    url(r'^files/',
        include(urlpatterns_files)),
    url(r'^create/$',
        views.songs_create,
        name='songs-create'),
    url(r'^create/import/$',
        views.songs_create_from_file,
        name='songs-create-from-file'),
    url(r'^(?P<song_id>\d+)/$',
        views.songs_read,
        name='songs-read'),
    url(r'^(?P<song_id>\d+)/update-lyrics/$',
        views.songs_update_lyrics,
        name='songs-update-lyrics'),
    url(r'^(?P<song_id>\d+)/update-properties/$',
        views.songs_update_properties,
        name='songs-update-properties'),
    url(r'^(?P<song_id>\d+)/delete/$',
        views.songs_delete,
        name='songs-delete'),
    url(r'^(?P<song_id>\d+)/delete/undo/$',
        views.songs_delete_undo,
        name='songs-delete-undo'),
    url(r'^(?P<song_id>\d+)/history-lyrics/$',
        views.songs_history_lyrics,
        name='songs-history-lyrics'),
    url(r'^(?P<song_id>\d+)/history-properties/$',
        views.songs_history_properties,
        name='songs-history-properties'),
    url(r'^(?P<song_id>\d+)/pptx/$',
        views.songs_make_pptx,
        name='songs-pptx'),
    url(r'^(?P<song_id>\d+)/xml/$',
        views.songs_make_xml,
        name='songs-xml'),
]

songs/views.py
# -*- coding: utf-8 -*-
"""
Views.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import io
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.servers.basehttp import FileWrapper
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from pptx import Presentation
from songs.models import Author, AuthorDetail, Songbook, SongbookDetail, SongAuthor, SongSongbook
from songs.models import PresentationStyle, Song, SongLyrics, Verse, File, check_verse_order_2
from songs.openlyrics import parse_xml, validate_xml_tree, xml_to_song


def songs_list(request):
    """
    List songs.
    :param request: HttpRequest
    :return: HttpResponse
    """
    ctx = dict()
    ctx['breadcrumb'] = [
        ('Inicio', reverse('start-page')),
        ('Lista de canciones', ),
    ]
    ctx['song_list'] = _get_current_song_list()

    return render(request, 'songs/song_list.html', ctx)


@login_required()
@permission_required('songs.delete_song', raise_exception=True)
def songs_list_deleted(request):
    """
    List deleted songs.
    :param request: HttpRequest
    :return: HttpResponse
    """
    ctx = dict()
    ctx['breadcrumb'] = [
        ('Inicio', reverse('start-page')),
        ('Canciones', reverse('songs:songs-list')),
        ('Canciones eliminadas', ),
    ]

    qs = SongLyrics.objects.filter(song__row_deleted=True, row_time_end__isnull=True)

    ctx['sf_text'] = request.GET.get('sf_text', '')
    q_t1 = Q(title_de__icontains=ctx['sf_text'])
    q_t2 = Q(title_en__icontains=ctx['sf_text'])
    q_t3 = Q(title_es__icontains=ctx['sf_text'])
    qs = qs.filter(q_t1 | q_t2 | q_t3)

    ctx['sf_order'] = '0'
    qs = qs.order_by('-row_time_start')

    ctx['sf'] = 'sf_text={}&sf_order={}'.format(
        ctx['sf_text'],
        ctx['sf_order'])

    for e in qs:
        e.url = reverse('songs:songs-read', args=[e.song.pk])

    paginator = Paginator(qs, 50)
    page = request.GET.get('page', 1)
    try:
        ctx['page'] = paginator.page(page)
    except PageNotAnInteger:
        ctx['page'] = paginator.page(1)
    except EmptyPage:
        ctx['page'] = paginator.page(paginator.num_pages)

    return render(request, 'songs/song_deleted_list.html', ctx)


@login_required()
@permission_required('songs.create_song', raise_exception=True)
def songs_create_from_file(request):
    """
    Create a song from an uploaded file.
    :param request: HttpRequest
    :return: HttpResponse
    """
    ctx = dict(page_title='Importar canción')
    ctx['breadcrumb'] = [
        ('Inicio', reverse('start-page')),
        ('Canciones', reverse('songs:songs-list')),
        ('Importar canción', ),
    ]

    if request.method == 'POST':
        file = request.FILES.get('song_file')
        if not file:
            messages.error(request, 'No se recibió ningún archivo.')
            return render(request, 'songs/song_upload_form.html', ctx)

        if request.POST.get('file_type') == 'xml':
            # read XML file
            try:
                tree = parse_xml(file)
            except SyntaxError as err:
                messages.error(request, 'El archivo no contiene XML válido. Error: "{}"'
                                        '.'.format(err))
                return render(request, 'songs/song_upload_form.html', ctx)

            try:
                validate_xml_tree(tree)
            except AssertionError as err:
                messages.error(request, 'El archivo no contiene una canción válida en formato '
                                        'OpenLyrics. Error: "{}".'.format(err))
                return render(request, 'songs/song_upload_form.html', ctx)

            try:
                new_lyrics, new_properties = xml_to_song(tree, request.user.username)
            except ValidationError as err:
                for msgs in err.message_dict.values():
                    for msg in msgs:
                        messages.error(request, msg)
                return render(request, 'songs/song_upload_form.html', ctx)
        else:
            # read PPTX file
            default_language = 'de'

            new_lyrics = dict()
            new_lyrics['title_de'] = 'PowerPoint'
            new_lyrics['singable_de'] = True
            new_lyrics['title_en'] = ''
            new_lyrics['singable_en'] = False
            new_lyrics['title_es'] = ''
            new_lyrics['singable_es'] = False
            new_lyrics['verse_order'] = ''
            new_lyrics['verse_list'] = []

            new_properties = dict()
            new_properties['songauthor_list'] = []
            new_properties['songsongbook_list'] = []
            new_properties['ccli_no'] = 0
            new_properties['variant'] = ''
            new_properties['version'] = ''
            new_properties['released'] = ''
            new_properties['publisher'] = ''
            new_properties['copyright'] = ''
            new_properties['keywords'] = ''
            new_properties['themes'] = ''
            new_properties['comments'] = ''
            new_properties['key'] = ''
            new_properties['transposition'] = 0
            new_properties['tempo'] = ''

            prs = Presentation(file)
            for i, slide in enumerate(prs.slides):
                paragraph_list = []
                for shape in slide.shapes:
                    if shape.has_text_frame:
                        for paragraph in shape.text_frame.paragraphs:
                            if paragraph.text.strip():
                                paragraph_list.append(paragraph.text.strip())
                new_content = _join_content(paragraph_list)

                if new_content:
                    if i == 0:      # slide with title
                        new_lyrics['title_de'] = new_content[:100]
                    else:
                        v = Verse()
                        v.language = default_language
                        v.name = 'v{}'.format(i)
                        v.content = new_content
                        new_lyrics['verse_list'].append(v)
            new_lyrics['verse_order'] = ' '.join(v.name for v in new_lyrics['verse_list'])

        song = Song()
        try:
            song.do_create_lyrics(user=request.user, **new_lyrics)
            song.do_create_properties(request.user)
            song.do_update_properties(user=request.user, **new_properties)
        except ValidationError as err:
            for msgs in err.message_dict.values():
                for msg in msgs:
                    messages.error(request, msg)
            return render(request, 'songs/song_upload_form.html', ctx)

        _clear_songs_cache()
        return redirect('songs:songs-read', song.pk)
    else:
        return render(request, 'songs/song_upload_form.html', ctx)


@login_required()
@permission_required('songs.create_song', raise_exception=True)
def songs_create(request):
    """
    Create a song.
    :param request: HttpRequest
    :return: HttpResponse
    """
    ctx = dict(page_title='Crear nueva canción')
    ctx['breadcrumb'] = [
        ('Inicio', reverse('start-page')),
        ('Canciones', reverse('songs:songs-list')),
        ('Crear nueva canción', ),
    ]
    ctx['CRUD'] = 'C'
    ctx['song'] = Song()
    return _songs_create_or_update_lyrics(request, ctx)


def songs_read(request, song_id):
    """
    Read a song.
    :param request: HttpRequest
    :param song_id:
    :return: HttpResponse
    """
    ctx = dict(page_title='Detalles de canción')
    ctx['breadcrumb'] = [
        ('Inicio', reverse('start-page')),
        ('Canciones', reverse('songs:songs-list')),
        ('Canción {}'.format(song_id), ),
    ]
    ctx['CRUD'] = 'R'
    ctx['song'] = get_object_or_404(Song, pk=song_id)

    ctx['song_lyrics'] = ctx['song'].current_lyrics
    ctx['verse_ordering'] = request.GET.get('verse_ordering', 'language')
    ctx['verse_list'] = sorted(
        ctx['song_lyrics'].verses.all(),
        key=lambda x: _get_sort_key(x.name, x.language, ctx['verse_ordering']))

    ctx['song_properties'] = ctx['song'].current_properties
    ctx['author_list'] = sorted(
        [str(e) for e in ctx['song_properties'].songauthor_set.all()])
    ctx['songbook_list'] = sorted(
        [str(e) for e in ctx['song_properties'].songsongbook_set.all()])

    ctx['presentation_styles'] = PresentationStyle.objects.order_by('pk')

    if ctx['song'].row_deleted:
        messages.error(request, 'Esta canción se encuentra en estado eliminado.')
        ctx['breadcrumb'].insert(
            2, ('Canciones eliminadas', reverse('songs:songs-list-deleted')))
    else:
        try:
            check_verse_order_2(ctx['song_lyrics'].verse_order, ctx['verse_list'])
        except ValidationError as err:
            for msgs in err.message_dict.values():
                for msg in msgs:
                    messages.warning(request, msg)

    return render(request, 'songs/song_read_form.html', ctx)


@login_required()
@permission_required('songs.update_song', raise_exception=True)
def songs_update_lyrics(request, song_id):
    """
    Update the lyrics of a song.
    :param request: HttpRequest
    :param song_id:
    :return: HttpResponse
    """
    ctx = dict(page_title='Modificar letra de canción')
    ctx['breadcrumb'] = [
        ('Inicio', reverse('start-page')),
        ('Canciones', reverse('songs:songs-list')),
        ('Canción {}'.format(song_id), reverse('songs:songs-read', args=[song_id])),
        ('Modificar letra', ),
    ]

songs/templates/songs/author_list.html
{% extends 'base_workspace.html' %}
{% load staticfiles %}

        {% block workspace %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="panel-title">
                                {% with breadcrumb|last as e %}{{ e.0 }}{% endwith %}
                            </span>
                            <div class="btn-group pull-right">
                                <a class="btn btn-sm btn-default" title="Filtros de búsqueda"
                                   href="#m_sf" role="button" data-toggle="modal">
                                    <span class="glyphicon glyphicon-search"></span>
                                </a>
                            {% if perms.songs.create_author %}
                                <a class="btn btn-sm btn-default" title="Crear nuevo autor"
                                   href="{% url 'songs:authors-create' %}">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </a>
                            {% endif %}
                            {% if perms.songs.delete_author %}
                                <a class="btn btn-sm btn-default" title="Ver autores eliminados"
                                   href="{% url 'songs:authors-list-deleted' %}">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            {% endif %}
                            </div>
                        </div>
                    {% if page.paginator.num_pages > 1 %}
                        {% include 'stub_paginator.html' with page=page params=sf only %}
                    {% endif %}
                        <div class="table-responsive">
                            <table class="table{% if page %} table-hover{% endif %}">
                                <thead>
                                    <tr>
                                        <th><span class="pull-right">#</span></th>
                                        <th>Nombre</th>
                                        <th>Canciones</th>
                                        <th>Tipo de autor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for elem in page %}
                                    <tr class="clickable-row" data-href="{{ elem.url|default:'#' }}">
                                        <td>
                                            <a href="{{ elem.url|default:'#' }}">
                                            {% if elem.is_header %}
                                                <span class="pull-right">
                                                    <strong>{{ elem.counter }}</strong>
                                                </span>
                                            {% endif %}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ elem.url|default:'#' }}">
                                            {% if elem.is_header %}
                                                <span title="{{ elem.name }}">
                                                    {{ elem.name|truncatechars:50 }}
                                                </span>
                                            {% endif %}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ elem.url|default:'#' }}">
                                            {% if not elem.is_header %}
                                                <span title="{{ elem.song_title }}">
                                                    {{ elem.counter }}.
                                                    {{ elem.song_title|truncatechars:30 }}
                                                </span>
                                            {% endif %}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ elem.url|default:'#' }}">
                                            {% if not elem.is_header %}
                                                {{ elem.type }}
                                            {% endif %}
                                            </a>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td></td>
                                        <td>No hay elementos para mostrar</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <!--search filter modal-->
            <div class="modal fade" id="m_sf" tabindex="-1" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">
                                <span>&times;</span>
                            </button>
                            <h4 class="modal-title">Filtros de búsqueda</h4>
                        </div>
                        <div class="modal-body">
                            <form class="form-horizontal" id="m_sf_form">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">Texto</label>
                                    <div class="col-sm-9">
                                        <input class="form-control" type="text" maxlength="50"
                                               id="m_sf_text" name="sf_text" value="{{ sf_text }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">Ordenar por</label>
                                    <div class="col-sm-5">
                                        <select class="form-control" name="sf_order">
                                            <option value="0" {% if sf_order == '0' %}selected{% endif %}>
                                                Nombre
                                            </option>
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" form="m_sf_form" class="btn btn-primary">
                                Buscar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}

    {% block javascript %}
        <script src="{% static 'js/base-list.js' %}"></script>
    {% endblock %}

songs/templates/songs/songbook_form.html
{% extends 'base_workspace.html' %}
{% load humanize %}

        {% block workspace %}
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'C' or CRUD == 'U' %}
                                <input class="form-control" type="text" name="name"
                                       value="{{ songbook.name }}" maxlength="100" autofocus>
                            {% else %}
                                <p class="form-control-static">{{ songbook.name }}</p>
                            {% endif %}
                            </div>
                        </div>
                        <div class="row form-button-row">
                            <div class="col-sm-12">
                        {% if CRUD == 'C' or CRUD == 'U' %}
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            {% if CRUD == 'C' %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'songs:songbooks-list' %}">
                                    Volver
                                </a>
                            {% else %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'songs:songbooks-read' songbook.pk %}">
                                    Cancelar
                                </a>
                            {% endif %}
                        {% elif CRUD == 'D' %}
                            {% if songbook.can_be_deleted %}
                                <button type="submit" class="btn btn-danger">
                                    Confirmar eliminación
                                </button>
                            {% endif %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'songs:songbooks-read' songbook.pk %}">
                                    Volver
                                </a>
                        {% else %}
                            {% if perms.songs.update_songbook and not songbook.row_deleted %}
                                <a class="btn btn-primary" role="button"
                                   href="{% url 'songs:songbooks-update' songbook.pk %}">
                                    Modificar
                                </a>
                            {% endif %}
                            {% if perms.songs.delete_songbook %}
                                {% if songbook.row_deleted %}
                                <button type="submit" form="undoDelete" class="btn btn-danger">
                                    Restaurar
                                </button>
                                {% else %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'songs:songbooks-delete' songbook.pk %}">
                                    Eliminar
                                </a>
                                {% endif %}
                            {% endif %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'songs:songbooks-list' %}">
                                    Volver
                                </a>
                        {% endif %}
                            </div>
                        </div>
                    </form>
                </div>

            {% if CRUD == 'R' %}
                {% if perms.songs.delete_songbook and songbook.row_deleted %}
                <form class="hidden" method="post" id="undoDelete"
                      action="{% url 'songs:songbooks-delete-undo' songbook.pk %}">
                    {% csrf_token %}
                </form>
                {% endif %}

                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <strong>Últimos cambios</strong>
                        {% if perms.songs.update_author %}
                            <div class="btn-group pull-right">
                                <a class="btn btn-xs btn-default" title="Ver historial de cambios"
                                   href="{% url 'songs:songbooks-history' songbook.pk %}">
                                    <span class="glyphicon glyphicon-time"></span>
                                </a>
                            </div>
                        {% endif %}
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Acción</th>
                                        <th>Fecha</th>
                                        <th>Usuario</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for elem in history_list %}
                                    <tr>
                                        <td>{{ elem.row_action }}</td>
                                        <td>
                                            {{ elem.row_time_start|date:'d-m-Y' }}
                                            <small>a las</small>
                                            {{ elem.row_time_start|date:'H:i' }}
                                            <small>
                                                ({{ elem.row_time_start|naturaltime }})
                                            </small>
                                        </td>
                                        <td>
                                            <span title="{{ elem.row_user_insert.profile }}">
                                                {{ elem.row_user_insert.profile|truncatechars:20 }}
                                            </span>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td></td>
                                        <td>No hay eventos para mostrar</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            {% endif %}

            </div>
        {% endblock %}