accounts/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from accounts import views, views_roles


users_urlpatterns = [
    url(r'^$',
        views.users_list,
        name='users-list'),
    url(r'^(?P<user_id>\d+)/$',
        views.users_read,
        name='users-read'),
    url(r'^(?P<user_id>\d+)/update/$',
        views.users_update,
        name='users-update'),
    url(r'^(?P<user_id>\d+)/activity/$',
        views.users_activity_list,
        name='users-activity-list'),
    url(r'^social-auth/$',
        views.social_auth_list,
        name='social-auth-list'),
]


roles_urlpatterns = [
    url(r'^$',
        views_roles.roles_list,
        name='roles-list'),
    url(r'^create/$',
        views_roles.roles_create,
        name='roles-create'),
    url(r'^(?P<role_id>\d+)/$',
        views_roles.roles_read,
        name='roles-read'),
    url(r'^(?P<role_id>\d+)/update/$',
        views_roles.roles_update,
        name='roles-update'),
    url(r'^(?P<role_id>\d+)/delete/$',
        views_roles.roles_delete,
        name='roles-delete'),
]


urlpatterns = [
    url(r'^login/$', views.login,
        name='login'),
    url(r'^login/error/$', views.login_error),
    url(r'^login/error/inactive/$', views.login_error, {'inactive_user': True}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'start-page'},
        name='logout'),
    url(r'^profile/$', views.profile,
        name='profile'),
    url(r'^profile/activity-list/$', views.profile_activity_list,
        name='profile-activity-list'),
    url(r'^profile/new/$', views.profile, {'new_user': True}),
    url(r'^profile/password/$', views.profile_password,
        name='profile-password'),
    url(r'^emails/$',
        views.email_list,
        name='email-list'),
    url(r'^sessions/$',
        views.session_list,
        name='session-list'),
    url(r'^status/$',
        views.system_status,
        name='system-status'),
    url(r'^users/', include(users_urlpatterns)),
    url(r'^roles/', include(roles_urlpatterns)),
]

mbg_websites/urls.py
# -*- coding: utf-8 -*-
"""
mbg_websites URL Configuration.

The 'urlpatterns' list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from mbg_websites import views


urlpatterns = [
    url(r'^$',
        views.start_page,
        name='start-page'),
    url(r'^about/$',
        views.about_page,
        name='about-page'),
    url(r'^help/$',
        views.help_page,
        name='help-page'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^people/', include('people.urls', namespace='people')),
    url(r'^planners/', include('planners.urls', namespace='planners')),
    url(r'^songs/', include('songs.urls', namespace='songs')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    # url(r'^.well-known/acme-challenge/.../$',
    #     views.certificate_challenge),
]

people/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2016 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from people import views_people, views_marriages, views_groups


marriage_urlpatterns = [
    url(r'^$',
        views_marriages.marriages_list,
        name='marriages-list'),
    url(r'^excel/$',
        views_marriages.marriages_list_excel,
        name='marriages-list-excel'),
    url(r'^deleted/$',
        views_marriages.marriages_list_deleted,
        name='marriages-list-deleted'),
    url(r'^create/$',
        views_marriages.marriages_create,
        name='marriages-create'),
    url(r'^(?P<marriage_id>\d+)/', include([
        url(r'^$',
            views_marriages.marriages_read,
            name='marriages-read'),
        url(r'^update/$',
            views_marriages.marriages_update,
            name='marriages-update'),
        url(r'^delete/$',
            views_marriages.marriages_delete,
            name='marriages-delete'),
        url(r'^delete/undo/$',
            views_marriages.marriages_delete_undo,
            name='marriages-delete-undo'),
        url(r'^history/$',
            views_marriages.marriages_history,
            name='marriages-history'),
    ])),
]


group_urlpatterns = [
    url(r'^$',
        views_groups.groups_list,
        name='groups-list'),
    url(r'^deleted/$',
        views_groups.groups_list_deleted,
        name='groups-list-deleted'),
    url(r'^create/$',
        views_groups.groups_create,
        name='groups-create'),
    url(r'^(?P<group_id>\d+)/', include([
        url(r'^$',
            views_groups.groups_read,
            name='groups-read'),
        url(r'^update/$',
            views_groups.groups_update,
            name='groups-update'),
        url(r'^delete/$',
            views_groups.groups_delete,
            name='groups-delete'),
        url(r'^delete/undo/$',
            views_groups.groups_delete_undo,
            name='groups-delete-undo'),
        url(r'^history/$',
            views_groups.groups_history,
            name='groups-history'),
        url(r'^members/', include([
            url(r'^excel/$',
                views_groups.groups_members_excel,
                name='groups-members-excel'),
            url(r'^pdf/$',
                views_groups.groups_members_pdf,
                name='groups-members-pdf'),
            url(r'^history/$',
                views_groups.groups_members_history,
                name='groups-members-history'),
        ])),
    ])),
]


urlpatterns = [
    url(r'^$',
        views_people.people_list,
        name='people-list'),
    url(r'^excel/$',
        views_people.people_list_excel,
        name='people-list-excel'),
    url(r'^excel/members/$',
        views_people.people_list_members_excel,
        name='people-list-members-excel'),
    url(r'^pdf/$',
        views_people.people_list_pdf,
        name='people-list-pdf'),
    url(r'^deleted/$',
        views_people.people_list_deleted,
        name='people-list-deleted'),
    url(r'^create/$',
        views_people.people_create,
        name='people-create'),
    url(r'^(?P<person_id>\d+)/', include([
        url(r'^$',
            views_people.people_read,
            name='people-read'),
        url(r'^update/$',
            views_people.people_update,
            name='people-update'),
        url(r'^delete/$',
            views_people.people_delete,
            name='people-delete'),
        url(r'^delete/undo/$',
            views_people.people_delete_undo,
            name='people-delete-undo'),
        url(r'^history/$',
            views_people.people_history,
            name='people-history'),
        url(r'^groups/', include([
            url(r'^history/$',
                views_people.people_groups_history,
                name='people-groups-history'),
            url(r'^add/$',
                views_people.people_groups_add,
                name='people-groups-add'),
            url(r'^edit/$',
                views_people.people_groups_edit,
                name='people-groups-edit'),
            url(r'^remove/$',
                views_people.people_groups_remove,
                name='people-groups-remove'),
        ])),
    ])),
    url(r'^birthdays/$',
        views_people.people_birthday_list,
        name='birthday-list'),
    url(r'^marriages/', include(marriage_urlpatterns)),
    url(r'^groups/', include(group_urlpatterns)),
]

songs/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from songs import views, views_authors, views_songbooks, views_styles, views_files


urlpatterns_authors = [
    url(r'^$',
        views_authors.authors_list,
        name='authors-list'),
    url(r'^deleted/$',
        views_authors.authors_list_deleted,
        name='authors-list-deleted'),
    url(r'^create/$',
        views_authors.authors_create,
        name='authors-create'),
    url(r'^(?P<author_id>\d+)/$',
        views_authors.authors_read,
        name='authors-read'),
    url(r'^(?P<author_id>\d+)/update/$',
        views_authors.authors_update,
        name='authors-update'),
    url(r'^(?P<author_id>\d+)/delete/$',
        views_authors.authors_delete,
        name='authors-delete'),
    url(r'^(?P<author_id>\d+)/delete/undo/$',
        views_authors.authors_delete_undo,
        name='authors-delete-undo'),
    url(r'^(?P<author_id>\d+)/history/$',
        views_authors.authors_history,
        name='authors-history'),
]


urlpatterns_songbooks = [
    url(r'^$',
        views_songbooks.songbooks_list,
        name='songbooks-list'),
    url(r'^deleted/$',
        views_songbooks.songbooks_list_deleted,
        name='songbooks-list-deleted'),
    url(r'^create/$',
        views_songbooks.songbooks_create,
        name='songbooks-create'),
    url(r'^(?P<songbook_id>\d+)/$',
        views_songbooks.songbooks_read,
        name='songbooks-read'),
    url(r'^(?P<songbook_id>\d+)/update/$',
        views_songbooks.songbooks_update,
        name='songbooks-update'),
    url(r'^(?P<songbook_id>\d+)/delete/$',
        views_songbooks.songbooks_delete,
        name='songbooks-delete'),
    url(r'^(?P<songbook_id>\d+)/delete/undo/$',
        views_songbooks.songbooks_delete_undo,
        name='songbooks-delete-undo'),
    url(r'^(?P<songbook_id>\d+)/history/$',
        views_songbooks.songbooks_history,
        name='songbooks-history'),
]


urlpatterns_styles = [
    url(r'^$',
        views_styles.styles_list,
        name='styles-list'),
    url(r'^create/$',
        views_styles.styles_create,
        name='styles-create'),
    url(r'^(?P<style_id>\d+)/$',
        views_styles.styles_read,
        name='styles-read'),
    url(r'^(?P<style_id>\d+)/update/$',
        views_styles.styles_update,
        name='styles-update'),
    url(r'^(?P<style_id>\d+)/delete/$',
        views_styles.styles_delete,
        name='styles-delete'),
]


urlpatterns_files = [
    url(r'^$',
        views_files.files_list,
        name='files-list'),
    url(r'^zip/$',
        views_files.files_download_zip,
        name='files-download-zip'),
    url(r'^zip/all-pptx/$',
        views_files.files_download_zip_pptx,
        name='files-download-zip-pptx'),
    url(r'^zip/all-xml/$',
        views_files.files_download_zip_xml,
        name='files-download-zip-xml'),
]


urlpatterns = [
    url(r'^$',
        views.songs_list,
        name='songs-list'),
    url(r'^deleted/$',
        views.songs_list_deleted,
        name='songs-list-deleted'),
    url(r'^authors/',
        include(urlpatterns_authors)),
    url(r'^songbooks/',
        include(urlpatterns_songbooks)),
    url(r'^styles/',
        include(urlpatterns_styles)),
    url(r'^files/',
        include(urlpatterns_files)),
    url(r'^create/$',
        views.songs_create,
        name='songs-create'),
    url(r'^create/import/$',
        views.songs_create_from_file,
        name='songs-create-from-file'),
    url(r'^(?P<song_id>\d+)/$',
        views.songs_read,
        name='songs-read'),
    url(r'^(?P<song_id>\d+)/update-lyrics/$',
        views.songs_update_lyrics,
        name='songs-update-lyrics'),
    url(r'^(?P<song_id>\d+)/update-properties/$',
        views.songs_update_properties,
        name='songs-update-properties'),
    url(r'^(?P<song_id>\d+)/delete/$',
        views.songs_delete,
        name='songs-delete'),
    url(r'^(?P<song_id>\d+)/delete/undo/$',
        views.songs_delete_undo,
        name='songs-delete-undo'),
    url(r'^(?P<song_id>\d+)/history-lyrics/$',
        views.songs_history_lyrics,
        name='songs-history-lyrics'),
    url(r'^(?P<song_id>\d+)/history-properties/$',
        views.songs_history_properties,
        name='songs-history-properties'),
    url(r'^(?P<song_id>\d+)/pptx/$',
        views.songs_make_pptx,
        name='songs-pptx'),
    url(r'^(?P<song_id>\d+)/xml/$',
        views.songs_make_xml,
        name='songs-xml'),
]

accounts/models.py
# -*- coding: utf-8 -*-
"""
Models.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.contrib.auth.models import User
from django.db import models
from people.models import Person


class UserProfile(models.Model):
    """
    This model represents the profile of a user, extending the default User model.
    """
    user = models.OneToOneField(User, related_name='profile', primary_key=True)
    person = models.ForeignKey(Person, null=True, blank=True, on_delete=models.PROTECT)
    row_time_insert = models.DateTimeField(auto_now_add=True)
    row_time_update = models.DateTimeField(auto_now=True)
    row_user_insert = models.ForeignKey(User, related_name='created_user_profiles',
                                        on_delete=models.PROTECT)
    row_user_update = models.ForeignKey(User, related_name='modified_user_profiles',
                                        on_delete=models.PROTECT)

    class Meta:
        default_permissions = ()
        permissions = (
            ('list_users', 'ver lista de usuarios'),
            ('update_user', 'modificar usuario'),
            ('list_calendars', 'ver lista de calendarios'),
            ('create_calendar', 'crear calendario'),
            ('delete_calendar', 'eliminar calendario'),
        )

    def __str__(self):
        if self.person:
            return str(self.person)
        else:
            return str(self.user)


class Log(models.Model):
    """
    Log of events.
    """
    EVENT_TYPES = (
        ('LOGIN', 'Inicio de sesión'),
        ('PW_CH', 'Cambio de contraseña'),
    )
    user = models.ForeignKey(User, related_name='log_entries', on_delete=models.PROTECT)
    type = models.CharField(max_length=5, choices=EVENT_TYPES, default='LOGIN',
                            error_messages={'blank': 'El tipo no puede quedar vacío.'})
    ip = models.CharField(max_length=20, default='',
                          error_messages={'blank': 'La IP no puede quedar vacía.'})
    row_time_insert = models.DateTimeField(auto_now_add=True)

    class Meta:
        default_permissions = ()
        ordering = ['-row_time_insert']

    def __str__(self):
        return 'Log(username: {}, type: {})'.format(self.user.username, self.type)

accounts/templates/accounts/profile_password.html
{% extends 'base_workspace.html' %}

        {% block workspace %}
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-8">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-4 control-label">Username</label>
                            <div class="col-sm-8">
                                <p class="form-control-static">{{ user.username }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">Contraseña actual</label>
                            <div class="col-sm-8">
                                <input class="form-control" type="password" name="oldPw" value=""
                                       maxlength="30" placeholder="Ingrese su contraseña actual"
                                       autocomplete="off" autofocus>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">Contraseña nueva</label>
                            <div class="col-sm-8">
                                <input class="form-control" type="password" name="newPw1" value=""
                                       maxlength="30" placeholder="Ingrese la nueva contraseña"
                                       autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-8 col-sm-offset-4">
                                <input class="form-control" type="password" name="newPw2" value=""
                                       maxlength="30" placeholder="Vuelva a ingresar la nueva contraseña"
                                       autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <p class="form-control-static text-justify">
                                    Usted tendrá que volver a iniciar sesión con la nueva contraseña
                                    después de guardar los cambios.
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <button type="submit" class="btn btn-primary">Cambiar</button>
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:profile' %}">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}

accounts/templates/accounts/role_form.html
{% extends 'base_workspace.html' %}

        {% block workspace %}
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'C' or CRUD == 'U' %}
                                <input class="form-control" type="text" name="name"
                                       value="{{ role.name }}" maxlength="50" autofocus>
                            {% else %}
                                <p class="form-control-static">{{ role.name }}</p>
                            {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Permisos</label>
                            <div class="col-sm-10">
                            {% for p in perm_list %}
                                <div class="checkbox">
                                    {{ forloop.counter }}.
                                    <label>
                                        <input type="checkbox" name="perms" value="{{ p.pk }}"
                                               {% if p in role.permissions.all %}checked{% endif %}
                                               {% if CRUD == 'R' or CRUD == 'D' %}disabled{% endif %}>
                                        {{ p.name }}
                                    </label>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                        <div class="row form-button-row">
                            <div class="col-sm-12">
                        {% if CRUD == 'C' or CRUD == 'U' %}
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            {% if CRUD == 'C' %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:roles-list' %}">
                                    Volver
                                </a>
                            {% else %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:roles-read' role.pk %}">
                                    Cancelar
                                </a>
                            {% endif %}
                        {% elif CRUD == 'D' %}
                                <button type="submit" class="btn btn-danger">
                                    Confirmar eliminación
                                </button>
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:roles-read' role.pk %}">
                                    Volver
                                </a>
                        {% else %}
                                <a class="btn btn-primary" role="button"
                                   href="{% url 'accounts:roles-update' role.pk %}">
                                    Modificar
                                </a>
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:roles-delete' role.pk %}">
                                    Eliminar
                                </a>
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:roles-list' %}">
                                    Volver
                                </a>
                        {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}

accounts/templates/accounts/user_form.html
{% extends 'base_workspace.html' %}
{% load staticfiles %}

    {% block css %}
        {{ block.super }}
        {% if CRUD == 'C' or CRUD == 'U' %}<link rel="stylesheet" href="{% static 'chosen/chosen.min.css' %}">{% endif %}
    {% endblock %}

        {% block workspace %}
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Username</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'U' and user.username == admin_username %}
                                <input class="form-control" type="text" name="username"
                                       value="{{ usr.username }}" maxlength="30" autofocus>
                            {% else %}
                                <p class="form-control-static">{{ usr.username }}</p>
                            {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Persona</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'U' %}
                                <select class="form-control" id="select_person" name="person">
                                    <option value="0"></option>
                                {% for e in person_list %}
                                    <option value="{{ e.pk }}" {% if usr.profile.person.pk == e.pk %}selected{% endif %}>
                                        {{ e.name }}
                                    </option>
                                {% endfor %}
                                </select>
                            {% else %}
                                <p class="form-control-static">
                                {% if usr.profile.person %}
                                    <a href="{% url 'people:people-read' usr.profile.person.pk %}">
                                        {{ usr.profile.person }}
                                    </a>
                                {% else %}
                                    (ninguna)
                                {% endif %}
                                </p>
                            {% endif %}
                            </div>
                        </div>
                    {% if CRUD == 'R' %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Tipo de acceso</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">
                            {% for e in auth_list %}
                                {% if e == 'facebook' %}
                                    <span class="text-primary">Facebook</span>{% if not forloop.last %},{% endif %}
                                {% elif e == 'google-oauth2' %}
                                    <span class="text-danger">Google</span>{% if not forloop.last %},{% endif %}
                                {% else %}
                                    {{ e|capfirst }}{% if not forloop.last %},{% endif %}
                                {% endif %}
                            {% endfor %}
                                </p>
                            </div>
                        </div>
                    {% endif %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Estado</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'U' %}
                                <label class="radio-inline">
                                    <input type="radio" name="status" value="A"
                                           {% if usr.is_active %}checked{% endif %}>
                                    <strong><span class="text-success">Activo</span></strong>
                                </label>
                                <label class="radio-inline">
                                    <input type="radio" name="status" value="I"
                                           {% if not usr.is_active %}checked{% endif %}>
                                    <strong><span class="text-danger">Inactivo</span></strong>
                                </label>
                            {% else %}
                                <p class="form-control-static">
                                {% if usr.is_active %}
                                    <strong><span class="text-success">Activo</span></strong>
                                {% else %}
                                    <strong><span class="text-danger">Inactivo</span></strong>
                                {% endif %}
                                </p>
                            {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Roles</label>
                            <div class="col-sm-10">
                            {% for g in perm_groups %}
                                <div class="checkbox">
                                    {{ forloop.counter }}.
                                    <label>
                                        <input type="checkbox" name="perm_groups" value="{{ g.pk }}"
                                               {% if usr.is_superuser or g in usr.groups.all %}checked{% endif %}
                                               {% if usr.is_superuser or CRUD == 'R' %}disabled{% endif %}>
                                        {{ g.name }}
                                    </label>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                        {% if CRUD == 'U' %}
                                <button type="submit" class="btn btn-primary">Guardar</button>
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:users-read' usr.pk %}">
                                    Cancelar
                                </a>
                        {% else %}
                            {% if perms.accounts.update_user and usr.username != admin_username %}
                                <a class="btn btn-primary" role="button"
                                   href="{% url 'accounts:users-update' usr.pk %}">
                                    Modificar
                                </a>
                            {% endif %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:users-activity-list' usr.pk %}">
                                    Ver acciones recientes
                                </a>
                                <a class="btn btn-default" role="button"
                                   href="{% url 'accounts:users-list' %}">
                                    Volver
                                </a>
                        {% endif %}
                            </div>
                        </div>

                        {% include 'stub_crud_access_info.html' with elem=usr.profile only %}
                    </form>
                </div>
            </div>
        {% endblock %}
    {% block javascript %}
        {% if CRUD == 'C' or CRUD == 'U' %}
        <script src="{% static 'chosen/chosen.jquery.min.js' %}"></script>
        <script type="text/javascript">
            (function () {  // start of closure
                $(document).ready(function () {
                    var opt2 = {
                        allow_single_deselect: true,
                        placeholder_text_single: 'Ninguna persona seleccionada',
                        no_results_text: 'No se encontró persona',
                        search_contains: true
                    };
                    $('#select_person').chosen(opt2);
                });
            })();   // end of closure
        </script>
        {% endif %}
    {% endblock %}