mbg_websites/urls.py
# -*- coding: utf-8 -*-
"""
mbg_websites URL Configuration.

The 'urlpatterns' list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from mbg_websites import views


urlpatterns = [
    url(r'^$',
        views.start_page,
        name='start-page'),
    url(r'^about/$',
        views.about_page,
        name='about-page'),
    url(r'^help/$',
        views.help_page,
        name='help-page'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^people/', include('people.urls', namespace='people')),
    url(r'^planners/', include('planners.urls', namespace='planners')),
    url(r'^songs/', include('songs.urls', namespace='songs')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    # url(r'^.well-known/acme-challenge/.../$',
    #     views.certificate_challenge),
]

people/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2016 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from people import views_people, views_marriages, views_groups


marriage_urlpatterns = [
    url(r'^$',
        views_marriages.marriages_list,
        name='marriages-list'),
    url(r'^excel/$',
        views_marriages.marriages_list_excel,
        name='marriages-list-excel'),
    url(r'^deleted/$',
        views_marriages.marriages_list_deleted,
        name='marriages-list-deleted'),
    url(r'^create/$',
        views_marriages.marriages_create,
        name='marriages-create'),
    url(r'^(?P<marriage_id>\d+)/', include([
        url(r'^$',
            views_marriages.marriages_read,
            name='marriages-read'),
        url(r'^update/$',
            views_marriages.marriages_update,
            name='marriages-update'),
        url(r'^delete/$',
            views_marriages.marriages_delete,
            name='marriages-delete'),
        url(r'^delete/undo/$',
            views_marriages.marriages_delete_undo,
            name='marriages-delete-undo'),
        url(r'^history/$',
            views_marriages.marriages_history,
            name='marriages-history'),
    ])),
]


group_urlpatterns = [
    url(r'^$',
        views_groups.groups_list,
        name='groups-list'),
    url(r'^deleted/$',
        views_groups.groups_list_deleted,
        name='groups-list-deleted'),
    url(r'^create/$',
        views_groups.groups_create,
        name='groups-create'),
    url(r'^(?P<group_id>\d+)/', include([
        url(r'^$',
            views_groups.groups_read,
            name='groups-read'),
        url(r'^update/$',
            views_groups.groups_update,
            name='groups-update'),
        url(r'^delete/$',
            views_groups.groups_delete,
            name='groups-delete'),
        url(r'^delete/undo/$',
            views_groups.groups_delete_undo,
            name='groups-delete-undo'),
        url(r'^history/$',
            views_groups.groups_history,
            name='groups-history'),
        url(r'^members/', include([
            url(r'^excel/$',
                views_groups.groups_members_excel,
                name='groups-members-excel'),
            url(r'^pdf/$',
                views_groups.groups_members_pdf,
                name='groups-members-pdf'),
            url(r'^history/$',
                views_groups.groups_members_history,
                name='groups-members-history'),
        ])),
    ])),
]


urlpatterns = [
    url(r'^$',
        views_people.people_list,
        name='people-list'),
    url(r'^excel/$',
        views_people.people_list_excel,
        name='people-list-excel'),
    url(r'^excel/members/$',
        views_people.people_list_members_excel,
        name='people-list-members-excel'),
    url(r'^pdf/$',
        views_people.people_list_pdf,
        name='people-list-pdf'),
    url(r'^deleted/$',
        views_people.people_list_deleted,
        name='people-list-deleted'),
    url(r'^create/$',
        views_people.people_create,
        name='people-create'),
    url(r'^(?P<person_id>\d+)/', include([
        url(r'^$',
            views_people.people_read,
            name='people-read'),
        url(r'^update/$',
            views_people.people_update,
            name='people-update'),
        url(r'^delete/$',
            views_people.people_delete,
            name='people-delete'),
        url(r'^delete/undo/$',
            views_people.people_delete_undo,
            name='people-delete-undo'),
        url(r'^history/$',
            views_people.people_history,
            name='people-history'),
        url(r'^groups/', include([
            url(r'^history/$',
                views_people.people_groups_history,
                name='people-groups-history'),
            url(r'^add/$',
                views_people.people_groups_add,
                name='people-groups-add'),
            url(r'^edit/$',
                views_people.people_groups_edit,
                name='people-groups-edit'),
            url(r'^remove/$',
                views_people.people_groups_remove,
                name='people-groups-remove'),
        ])),
    ])),
    url(r'^birthdays/$',
        views_people.people_birthday_list,
        name='birthday-list'),
    url(r'^marriages/', include(marriage_urlpatterns)),
    url(r'^groups/', include(group_urlpatterns)),
]

songs/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from songs import views, views_authors, views_songbooks, views_styles, views_files


urlpatterns_authors = [
    url(r'^$',
        views_authors.authors_list,
        name='authors-list'),
    url(r'^deleted/$',
        views_authors.authors_list_deleted,
        name='authors-list-deleted'),
    url(r'^create/$',
        views_authors.authors_create,
        name='authors-create'),
    url(r'^(?P<author_id>\d+)/$',
        views_authors.authors_read,
        name='authors-read'),
    url(r'^(?P<author_id>\d+)/update/$',
        views_authors.authors_update,
        name='authors-update'),
    url(r'^(?P<author_id>\d+)/delete/$',
        views_authors.authors_delete,
        name='authors-delete'),
    url(r'^(?P<author_id>\d+)/delete/undo/$',
        views_authors.authors_delete_undo,
        name='authors-delete-undo'),
    url(r'^(?P<author_id>\d+)/history/$',
        views_authors.authors_history,
        name='authors-history'),
]


urlpatterns_songbooks = [
    url(r'^$',
        views_songbooks.songbooks_list,
        name='songbooks-list'),
    url(r'^deleted/$',
        views_songbooks.songbooks_list_deleted,
        name='songbooks-list-deleted'),
    url(r'^create/$',
        views_songbooks.songbooks_create,
        name='songbooks-create'),
    url(r'^(?P<songbook_id>\d+)/$',
        views_songbooks.songbooks_read,
        name='songbooks-read'),
    url(r'^(?P<songbook_id>\d+)/update/$',
        views_songbooks.songbooks_update,
        name='songbooks-update'),
    url(r'^(?P<songbook_id>\d+)/delete/$',
        views_songbooks.songbooks_delete,
        name='songbooks-delete'),
    url(r'^(?P<songbook_id>\d+)/delete/undo/$',
        views_songbooks.songbooks_delete_undo,
        name='songbooks-delete-undo'),
    url(r'^(?P<songbook_id>\d+)/history/$',
        views_songbooks.songbooks_history,
        name='songbooks-history'),
]


urlpatterns_styles = [
    url(r'^$',
        views_styles.styles_list,
        name='styles-list'),
    url(r'^create/$',
        views_styles.styles_create,
        name='styles-create'),
    url(r'^(?P<style_id>\d+)/$',
        views_styles.styles_read,
        name='styles-read'),
    url(r'^(?P<style_id>\d+)/update/$',
        views_styles.styles_update,
        name='styles-update'),
    url(r'^(?P<style_id>\d+)/delete/$',
        views_styles.styles_delete,
        name='styles-delete'),
]


urlpatterns_files = [
    url(r'^$',
        views_files.files_list,
        name='files-list'),
    url(r'^zip/$',
        views_files.files_download_zip,
        name='files-download-zip'),
    url(r'^zip/all-pptx/$',
        views_files.files_download_zip_pptx,
        name='files-download-zip-pptx'),
    url(r'^zip/all-xml/$',
        views_files.files_download_zip_xml,
        name='files-download-zip-xml'),
]


urlpatterns = [
    url(r'^$',
        views.songs_list,
        name='songs-list'),
    url(r'^deleted/$',
        views.songs_list_deleted,
        name='songs-list-deleted'),
    url(r'^authors/',
        include(urlpatterns_authors)),
    url(r'^songbooks/',
        include(urlpatterns_songbooks)),
    url(r'^styles/',
        include(urlpatterns_styles)),
    url(r'^files/',
        include(urlpatterns_files)),
    url(r'^create/$',
        views.songs_create,
        name='songs-create'),
    url(r'^create/import/$',
        views.songs_create_from_file,
        name='songs-create-from-file'),
    url(r'^(?P<song_id>\d+)/$',
        views.songs_read,
        name='songs-read'),
    url(r'^(?P<song_id>\d+)/update-lyrics/$',
        views.songs_update_lyrics,
        name='songs-update-lyrics'),
    url(r'^(?P<song_id>\d+)/update-properties/$',
        views.songs_update_properties,
        name='songs-update-properties'),
    url(r'^(?P<song_id>\d+)/delete/$',
        views.songs_delete,
        name='songs-delete'),
    url(r'^(?P<song_id>\d+)/delete/undo/$',
        views.songs_delete_undo,
        name='songs-delete-undo'),
    url(r'^(?P<song_id>\d+)/history-lyrics/$',
        views.songs_history_lyrics,
        name='songs-history-lyrics'),
    url(r'^(?P<song_id>\d+)/history-properties/$',
        views.songs_history_properties,
        name='songs-history-properties'),
    url(r'^(?P<song_id>\d+)/pptx/$',
        views.songs_make_pptx,
        name='songs-pptx'),
    url(r'^(?P<song_id>\d+)/xml/$',
        views.songs_make_xml,
        name='songs-xml'),
]

accounts/models.py
# -*- coding: utf-8 -*-
"""
Models.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.contrib.auth.models import User
from django.db import models
from people.models import Person


class UserProfile(models.Model):
    """
    This model represents the profile of a user, extending the default User model.
    """
    user = models.OneToOneField(User, related_name='profile', primary_key=True)
    person = models.ForeignKey(Person, null=True, blank=True, on_delete=models.PROTECT)
    row_time_insert = models.DateTimeField(auto_now_add=True)
    row_time_update = models.DateTimeField(auto_now=True)
    row_user_insert = models.ForeignKey(User, related_name='created_user_profiles',
                                        on_delete=models.PROTECT)
    row_user_update = models.ForeignKey(User, related_name='modified_user_profiles',
                                        on_delete=models.PROTECT)

    class Meta:
        default_permissions = ()
        permissions = (
            ('list_users', 'ver lista de usuarios'),
            ('update_user', 'modificar usuario'),
            ('list_calendars', 'ver lista de calendarios'),
            ('create_calendar', 'crear calendario'),
            ('delete_calendar', 'eliminar calendario'),
        )

    def __str__(self):
        if self.person:
            return str(self.person)
        else:
            return str(self.user)


class Log(models.Model):
    """
    Log of events.
    """
    EVENT_TYPES = (
        ('LOGIN', 'Inicio de sesión'),
        ('PW_CH', 'Cambio de contraseña'),
    )
    user = models.ForeignKey(User, related_name='log_entries', on_delete=models.PROTECT)
    type = models.CharField(max_length=5, choices=EVENT_TYPES, default='LOGIN',
                            error_messages={'blank': 'El tipo no puede quedar vacío.'})
    ip = models.CharField(max_length=20, default='',
                          error_messages={'blank': 'La IP no puede quedar vacía.'})
    row_time_insert = models.DateTimeField(auto_now_add=True)

    class Meta:
        default_permissions = ()
        ordering = ['-row_time_insert']

    def __str__(self):
        return 'Log(username: {}, type: {})'.format(self.user.username, self.type)

people/templates/people/group_form.html
{% extends 'base_workspace.html' %}
{% load humanize %}

        {% block workspace %}
            <div class="row">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <form class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Tipo</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'C' or CRUD == 'U' %}
                                <select class="form-control" name="type" autofocus>
                                {% for e in group_type_list %}
                                    <option value="{{ e.0 }}" {% if e.0 == current_details.type %}selected{% endif %}>
                                        {{ e.1 }}
                                    </option>
                                {% endfor %}
                                </select>
                            {% else %}
                                <p class="form-control-static">{{ current_details.get_type_display }}</p>
                            {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'C' or CRUD == 'U' %}
                                <input class="form-control" type="text" name="name"
                                       value="{{ current_details.name }}" maxlength="50"
                                       placeholder="Dato requerido">
                            {% else %}
                                <p class="form-control-static">{{ current_details.name }}</p>
                            {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Observación</label>
                            <div class="col-sm-10">
                            {% if CRUD == 'C' or CRUD == 'U' %}
                                <input class="form-control" type="text" name="obs"
                                       value="{{ current_details.obs }}" maxlength="1000">
                            {% else %}
                                <p class="form-control-static">{{ current_details.obs }}</p>
                            {% endif %}
                            </div>
                        </div>
                        <div class="row form-button-row">
                            <div class="col-sm-12">
                        {% if CRUD == 'C' or CRUD == 'U' %}
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            {% if CRUD == 'C' %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'people:groups-list' %}">
                                    Volver
                                </a>
                            {% else %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'people:groups-read' group.pk %}">
                                    Cancelar
                                </a>
                            {% endif %}
                        {% elif CRUD == 'D' %}
                            {% if group.can_be_deleted %}
                                <button type="submit" class="btn btn-danger">
                                    Confirmar eliminación
                                </button>
                            {% endif %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'people:groups-read' group.pk %}">
                                    Volver
                                </a>
                        {% else %}
                            {% if perms.people.update_group and not group.row_deleted %}
                                <a class="btn btn-primary" role="button"
                                   href="{% url 'people:groups-update' group.pk %}">
                                    Modificar
                                </a>
                            {% endif %}
                            {% if perms.people.delete_group %}
                                {% if group.row_deleted %}
                                <button type="submit" form="undoDelete" class="btn btn-danger">
                                    Restaurar
                                </button>
                                {% else %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'people:groups-delete' group.pk %}">
                                    Eliminar
                                </a>
                                {% endif %}
                            {% endif %}
                                <a class="btn btn-default" role="button"
                                   href="{% url 'people:groups-list' %}">
                                    Volver
                                </a>
                        {% endif %}
                            </div>
                        </div>
                    </form>
                </div>

            {% if CRUD == 'R' %}
                {% if perms.people.delete_group and group.row_deleted %}
                <form class="hidden" method="post" id="undoDelete"
                      action="{% url 'people:groups-delete-undo' group.pk %}">
                    {% csrf_token %}
                </form>
                {% endif %}

                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <strong>
                                Miembros
                                <small>({{ group.current_member_count }})</small>
                            </strong>
                            <div class="btn-group pull-right">
                                <a class="btn btn-xs btn-default" title="Ver historial de cambios"
                                   href="{% url 'people:groups-members-history' group.pk %}">
                                    <span class="glyphicon glyphicon-time"></span>
                                </a>
                                <button type="button" class="btn btn-xs btn-default dropdown-toggle"
                                        data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-file"></span>
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <a href="{% url 'people:groups-members-excel' group.pk %}">
                                            <span class="text-success">
                                                <small><strong>EXCEL</strong></small>
                                            </span>
                                            - Lista de miembros
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'people:groups-members-pdf' group.pk %}" target="_blank">
                                            <span class="text-danger">
                                                <small><strong>PDF</strong></small>
                                            </span>
                                            - Lista de miembros
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Apellido</th>
                                        <th><span class="pull-right">Edad</span></th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for elem in group.sorted_current_members %}
                                    <tr>
                                    {% with d=elem.person.current_details %}
                                        <td>
                                            <a href="{% url 'people:people-read' d.person.pk %}"
                                               title="{{ d.first_name }}">
                                                {{ d.first_name|truncatechars:20 }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'people:people-read' d.person.pk %}"
                                               title="{{ d.last_name }}">
                                                {{ d.last_name|truncatechars:20 }}
                                            </a>
                                        </td>
                                        <td>
                                            <span class="pull-right"
                                                  {% if d.death_date %}title="Fallecido"{% endif %}>
                                                {% if d.death_date %}&#10015;{% endif %}
                                                {{ d.age }}
                                            </span>
                                        </td>
                                    {% endwith %}
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td>No hay miembros para mostrar</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-md-8 col-sm-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <strong>Últimos cambios</strong>
                        {% if perms.people.update_group %}
                            <div class="btn-group pull-right">
                                <a class="btn btn-xs btn-default" title="Ver historial de cambios"
                                   href="{% url 'people:groups-history' group.pk %}">
                                    <span class="glyphicon glyphicon-time"></span>
                                </a>
                            </div>
                        {% endif %}
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Acción</th>
                                        <th>Fecha</th>
                                        <th>Usuario</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for elem in history_list %}
                                    <tr>
                                        <td>{{ elem.row_action }}</td>
                                        <td>
                                            {{ elem.row_time_start|date:'d-m-Y' }}
                                            <small>a las</small>
                                            {{ elem.row_time_start|date:'H:i' }}
                                            <small>
                                                ({{ elem.row_time_start|naturaltime }})
                                            </small>
                                        </td>
                                        <td>
                                            <span title="{{ elem.row_user_insert.profile }}">
                                                {{ elem.row_user_insert.profile|truncatechars:20 }}
                                            </span>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td></td>
                                        <td>No hay eventos para mostrar</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            {% endif %}

            </div>
        {% endblock %}

people/templates/people/group_list.html
{% extends 'base_list.html' %}

                        {% block panel_buttons %}
                            {% if perms.people.create_group %}
                                <a class="btn btn-sm btn-default" title="Crear nuevo grupo"
                                   href="{% url 'people:groups-create' %}">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </a>
                            {% endif %}
                            {% if perms.people.delete_group %}
                                <a class="btn btn-sm btn-default" title="Ver grupos eliminados"
                                   href="{% url 'people:groups-list-deleted' %}">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            {% endif %}
                        {% endblock %}

                                    {% block table_header %}
                                        <th>Tipo</th>
                                        <th>Nombre</th>
                                        <th><span class="pull-right">Miembros</span></th>
                                    {% endblock %}

                                    {% block table_row_content %}
                                        <td>
                                            <a href="{{ elem.url|default:'#' }}">
                                                {{ elem.get_type_display }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ elem.url|default:'#' }}">
                                                {{ elem.name }}
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{{ elem.url|default:'#' }}">
                                                <span class="pull-right">
                                                    {{ elem.group.current_member_count }}
                                                </span>
                                            </a>
                                        </td>
                                    {% endblock %}

                            {% block m_sf_content_dates %}
                            {% endblock %}

                            {% block m_sf_content_other %}
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">Tipo</label>
                                    <div class="col-sm-5">
                                        <select class="form-control" name="sf_type">
                                            <option value="A" {% if sf_type == 'A' %}selected{% endif %}>
                                                (Todos)
                                            </option>
                                        {% for e in group_type_list %}
                                            <option value="{{ e.0 }}" {% if sf_type == e.0 %}selected{% endif %}>
                                                {{ e.1 }}
                                            </option>
                                        {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            {% endblock %}

                                        {% block m_sf_content_order %}
                                            <option value="0" {% if sf_order == '0' %}selected{% endif %}>
                                                Tipo, nombre
                                            </option>
                                        {% endblock %}