accounts/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from accounts import views, views_roles


users_urlpatterns = [
    url(r'^$',
        views.users_list,
        name='users-list'),
    url(r'^(?P<user_id>\d+)/$',
        views.users_read,
        name='users-read'),
    url(r'^(?P<user_id>\d+)/update/$',
        views.users_update,
        name='users-update'),
    url(r'^(?P<user_id>\d+)/activity/$',
        views.users_activity_list,
        name='users-activity-list'),
    url(r'^social-auth/$',
        views.social_auth_list,
        name='social-auth-list'),
]


roles_urlpatterns = [
    url(r'^$',
        views_roles.roles_list,
        name='roles-list'),
    url(r'^create/$',
        views_roles.roles_create,
        name='roles-create'),
    url(r'^(?P<role_id>\d+)/$',
        views_roles.roles_read,
        name='roles-read'),
    url(r'^(?P<role_id>\d+)/update/$',
        views_roles.roles_update,
        name='roles-update'),
    url(r'^(?P<role_id>\d+)/delete/$',
        views_roles.roles_delete,
        name='roles-delete'),
]


urlpatterns = [
    url(r'^login/$', views.login,
        name='login'),
    url(r'^login/error/$', views.login_error),
    url(r'^login/error/inactive/$', views.login_error, {'inactive_user': True}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': 'start-page'},
        name='logout'),
    url(r'^profile/$', views.profile,
        name='profile'),
    url(r'^profile/activity-list/$', views.profile_activity_list,
        name='profile-activity-list'),
    url(r'^profile/new/$', views.profile, {'new_user': True}),
    url(r'^profile/password/$', views.profile_password,
        name='profile-password'),
    url(r'^emails/$',
        views.email_list,
        name='email-list'),
    url(r'^sessions/$',
        views.session_list,
        name='session-list'),
    url(r'^status/$',
        views.system_status,
        name='system-status'),
    url(r'^users/', include(users_urlpatterns)),
    url(r'^roles/', include(roles_urlpatterns)),
]

mbg_websites/urls.py
# -*- coding: utf-8 -*-
"""
mbg_websites URL Configuration.

The 'urlpatterns' list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from mbg_websites import views


urlpatterns = [
    url(r'^$',
        views.start_page,
        name='start-page'),
    url(r'^about/$',
        views.about_page,
        name='about-page'),
    url(r'^help/$',
        views.help_page,
        name='help-page'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^people/', include('people.urls', namespace='people')),
    url(r'^planners/', include('planners.urls', namespace='planners')),
    url(r'^songs/', include('songs.urls', namespace='songs')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    # url(r'^.well-known/acme-challenge/.../$',
    #     views.certificate_challenge),
]

people/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2016 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from people import views_people, views_marriages, views_groups


marriage_urlpatterns = [
    url(r'^$',
        views_marriages.marriages_list,
        name='marriages-list'),
    url(r'^excel/$',
        views_marriages.marriages_list_excel,
        name='marriages-list-excel'),
    url(r'^deleted/$',
        views_marriages.marriages_list_deleted,
        name='marriages-list-deleted'),
    url(r'^create/$',
        views_marriages.marriages_create,
        name='marriages-create'),
    url(r'^(?P<marriage_id>\d+)/', include([
        url(r'^$',
            views_marriages.marriages_read,
            name='marriages-read'),
        url(r'^update/$',
            views_marriages.marriages_update,
            name='marriages-update'),
        url(r'^delete/$',
            views_marriages.marriages_delete,
            name='marriages-delete'),
        url(r'^delete/undo/$',
            views_marriages.marriages_delete_undo,
            name='marriages-delete-undo'),
        url(r'^history/$',
            views_marriages.marriages_history,
            name='marriages-history'),
    ])),
]


group_urlpatterns = [
    url(r'^$',
        views_groups.groups_list,
        name='groups-list'),
    url(r'^deleted/$',
        views_groups.groups_list_deleted,
        name='groups-list-deleted'),
    url(r'^create/$',
        views_groups.groups_create,
        name='groups-create'),
    url(r'^(?P<group_id>\d+)/', include([
        url(r'^$',
            views_groups.groups_read,
            name='groups-read'),
        url(r'^update/$',
            views_groups.groups_update,
            name='groups-update'),
        url(r'^delete/$',
            views_groups.groups_delete,
            name='groups-delete'),
        url(r'^delete/undo/$',
            views_groups.groups_delete_undo,
            name='groups-delete-undo'),
        url(r'^history/$',
            views_groups.groups_history,
            name='groups-history'),
        url(r'^members/', include([
            url(r'^excel/$',
                views_groups.groups_members_excel,
                name='groups-members-excel'),
            url(r'^pdf/$',
                views_groups.groups_members_pdf,
                name='groups-members-pdf'),
            url(r'^history/$',
                views_groups.groups_members_history,
                name='groups-members-history'),
        ])),
    ])),
]


urlpatterns = [
    url(r'^$',
        views_people.people_list,
        name='people-list'),
    url(r'^excel/$',
        views_people.people_list_excel,
        name='people-list-excel'),
    url(r'^excel/members/$',
        views_people.people_list_members_excel,
        name='people-list-members-excel'),
    url(r'^pdf/$',
        views_people.people_list_pdf,
        name='people-list-pdf'),
    url(r'^deleted/$',
        views_people.people_list_deleted,
        name='people-list-deleted'),
    url(r'^create/$',
        views_people.people_create,
        name='people-create'),
    url(r'^(?P<person_id>\d+)/', include([
        url(r'^$',
            views_people.people_read,
            name='people-read'),
        url(r'^update/$',
            views_people.people_update,
            name='people-update'),
        url(r'^delete/$',
            views_people.people_delete,
            name='people-delete'),
        url(r'^delete/undo/$',
            views_people.people_delete_undo,
            name='people-delete-undo'),
        url(r'^history/$',
            views_people.people_history,
            name='people-history'),
        url(r'^groups/', include([
            url(r'^history/$',
                views_people.people_groups_history,
                name='people-groups-history'),
            url(r'^add/$',
                views_people.people_groups_add,
                name='people-groups-add'),
            url(r'^edit/$',
                views_people.people_groups_edit,
                name='people-groups-edit'),
            url(r'^remove/$',
                views_people.people_groups_remove,
                name='people-groups-remove'),
        ])),
    ])),
    url(r'^birthdays/$',
        views_people.people_birthday_list,
        name='birthday-list'),
    url(r'^marriages/', include(marriage_urlpatterns)),
    url(r'^groups/', include(group_urlpatterns)),
]

planners/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2016 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from planners import views, views_calendars, views_events


events_urlpatterns = [
    url(r'^$',
        views_events.events_list,
        name='events-list'),
    url(r'^deleted/$',
        views_events.events_list_deleted,
        name='events-list-deleted'),
    url(r'^create/$',
        views_events.events_create,
        name='events-create'),
    url(r'^(?P<event_id>\d+)/', include([
        url(r'^$',
            views_events.events_read,
            name='events-read'),
        url(r'^update/$',
            views_events.events_update,
            name='events-update'),
        url(r'^delete/$',
            views_events.events_delete,
            name='events-delete'),
        url(r'^delete/undo/$',
            views_events.events_delete_undo,
            name='events-delete-undo'),
        url(r'^history/$',
            views_events.events_history,
            name='events-history'),
        url(r'^sync/$',
            views_events.events_sync,
            name='events-sync'),
        url(r'^responsibilities/', include([
            url(r'^history/$',
                views_events.events_responsibilities_history,
                name='events-responsibilities-history'),
            url(r'^add/$',
                views_events.events_responsibilities_add,
                name='events-responsibilities-add'),
            url(r'^edit/$',
                views_events.events_responsibilities_edit,
                name='events-responsibilities-edit'),
            url(r'^remove/$',
                views_events.events_responsibilities_remove,
                name='events-responsibilities-remove'),
        ])),
        url(r'^schedule/', include([
            url(r'^history/$',
                views_events.events_schedule_history,
                name='events-schedule-history'),
            url(r'^add/$',
                views_events.events_schedule_add,
                name='events-schedule-add'),
            url(r'^edit/$',
                views_events.events_schedule_edit,
                name='events-schedule-edit'),
            url(r'^remove/$',
                views_events.events_schedule_remove,
                name='events-schedule-remove'),
            url(r'^pdf/$',
                views_events.events_schedule_pdf,
                name='events-schedule-pdf'),
        ])),
    ])),
]


calendar_urlpatterns = [
    url(r'^$',
        views_calendars.calendars_read,
        name='calendars-read'),
    url(r'^update/$',
        views_calendars.calendars_update,
        name='calendars-update'),
    url(r'^delete/$',
        views_calendars.calendars_delete,
        name='calendars-delete'),
    url(r'^delete/undo/$',
        views_calendars.calendars_delete_undo,
        name='calendars-delete-undo'),
    url(r'^history/$',
        views_calendars.calendars_history,
        name='calendars-history'),
    url(r'^sync/$',
        views_calendars.calendars_sync,
        name='calendars-sync'),
    url(r'^assign-perms/$',
        views_calendars.calendars_assign_perms,
        name='calendars-assign-perms'),
    url(r'^add-user/$',
        views_calendars.calendars_add_user,
        name='calendars-add-user'),
    url(r'^remove-user/$',
        views_calendars.calendars_remove_user,
        name='calendars-remove-user'),
    url(r'^events/', include(events_urlpatterns)),
]


calendars_urlpatterns = [
    url(r'^$',
        views_calendars.calendars_list,
        name='calendars-list'),
    url(r'^deleted/$',
        views_calendars.calendars_list_deleted,
        name='calendars-list-deleted'),
    url(r'^create/$',
        views_calendars.calendars_create,
        name='calendars-create'),
    url(r'^(?P<calendar_id>\d+)/', include(calendar_urlpatterns)),
]


urlpatterns = [
    url(r'^$',
        views.planners_start_page,
        name='start-page'),
    url(r'^calendars/', include(calendars_urlpatterns)),
    url(r'^events/', include([
        url(r'^$',
            views_events.events_list_all,
            name='events-list-all'),
        url(r'^editable/$',
            views_events.events_list_editable,
            name='events-editable'),
        url(r'^editable/pdf/$',
            views_events.events_list_editable_pdf,
            name='events-editable-pdf'),
    ])),
    url(r'^events/json/$',
        views.events_json,
        name='events-json'),
    url(r'^user-colors/$',
        views.user_colors,
        name='user-colors'),
    url(r'^user-responsibilities/$',
        views.user_responsibilities,
        name='user-responsibilities'),
]

songs/urls.py
# -*- coding: utf-8 -*-
"""
URL configuration.
"""

# Copyright (C) 2015 Ralf Funk
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import url, include
from songs import views, views_authors, views_songbooks, views_styles, views_files


urlpatterns_authors = [
    url(r'^$',
        views_authors.authors_list,
        name='authors-list'),
    url(r'^deleted/$',
        views_authors.authors_list_deleted,
        name='authors-list-deleted'),
    url(r'^create/$',
        views_authors.authors_create,
        name='authors-create'),
    url(r'^(?P<author_id>\d+)/$',
        views_authors.authors_read,
        name='authors-read'),
    url(r'^(?P<author_id>\d+)/update/$',
        views_authors.authors_update,
        name='authors-update'),
    url(r'^(?P<author_id>\d+)/delete/$',
        views_authors.authors_delete,
        name='authors-delete'),
    url(r'^(?P<author_id>\d+)/delete/undo/$',
        views_authors.authors_delete_undo,
        name='authors-delete-undo'),
    url(r'^(?P<author_id>\d+)/history/$',
        views_authors.authors_history,
        name='authors-history'),
]


urlpatterns_songbooks = [
    url(r'^$',
        views_songbooks.songbooks_list,
        name='songbooks-list'),
    url(r'^deleted/$',
        views_songbooks.songbooks_list_deleted,
        name='songbooks-list-deleted'),
    url(r'^create/$',
        views_songbooks.songbooks_create,
        name='songbooks-create'),
    url(r'^(?P<songbook_id>\d+)/$',
        views_songbooks.songbooks_read,
        name='songbooks-read'),
    url(r'^(?P<songbook_id>\d+)/update/$',
        views_songbooks.songbooks_update,
        name='songbooks-update'),
    url(r'^(?P<songbook_id>\d+)/delete/$',
        views_songbooks.songbooks_delete,
        name='songbooks-delete'),
    url(r'^(?P<songbook_id>\d+)/delete/undo/$',
        views_songbooks.songbooks_delete_undo,
        name='songbooks-delete-undo'),
    url(r'^(?P<songbook_id>\d+)/history/$',
        views_songbooks.songbooks_history,
        name='songbooks-history'),
]


urlpatterns_styles = [
    url(r'^$',
        views_styles.styles_list,
        name='styles-list'),
    url(r'^create/$',
        views_styles.styles_create,
        name='styles-create'),
    url(r'^(?P<style_id>\d+)/$',
        views_styles.styles_read,
        name='styles-read'),
    url(r'^(?P<style_id>\d+)/update/$',
        views_styles.styles_update,
        name='styles-update'),
    url(r'^(?P<style_id>\d+)/delete/$',
        views_styles.styles_delete,
        name='styles-delete'),
]


urlpatterns_files = [
    url(r'^$',
        views_files.files_list,
        name='files-list'),
    url(r'^zip/$',
        views_files.files_download_zip,
        name='files-download-zip'),
    url(r'^zip/all-pptx/$',
        views_files.files_download_zip_pptx,
        name='files-download-zip-pptx'),
    url(r'^zip/all-xml/$',
        views_files.files_download_zip_xml,
        name='files-download-zip-xml'),
]


urlpatterns = [
    url(r'^$',
        views.songs_list,
        name='songs-list'),
    url(r'^deleted/$',
        views.songs_list_deleted,
        name='songs-list-deleted'),
    url(r'^authors/',
        include(urlpatterns_authors)),
    url(r'^songbooks/',
        include(urlpatterns_songbooks)),
    url(r'^styles/',
        include(urlpatterns_styles)),
    url(r'^files/',
        include(urlpatterns_files)),
    url(r'^create/$',
        views.songs_create,
        name='songs-create'),
    url(r'^create/import/$',
        views.songs_create_from_file,
        name='songs-create-from-file'),
    url(r'^(?P<song_id>\d+)/$',
        views.songs_read,
        name='songs-read'),
    url(r'^(?P<song_id>\d+)/update-lyrics/$',
        views.songs_update_lyrics,
        name='songs-update-lyrics'),
    url(r'^(?P<song_id>\d+)/update-properties/$',
        views.songs_update_properties,
        name='songs-update-properties'),
    url(r'^(?P<song_id>\d+)/delete/$',
        views.songs_delete,
        name='songs-delete'),
    url(r'^(?P<song_id>\d+)/delete/undo/$',
        views.songs_delete_undo,
        name='songs-delete-undo'),
    url(r'^(?P<song_id>\d+)/history-lyrics/$',
        views.songs_history_lyrics,
        name='songs-history-lyrics'),
    url(r'^(?P<song_id>\d+)/history-properties/$',
        views.songs_history_properties,
        name='songs-history-properties'),
    url(r'^(?P<song_id>\d+)/pptx/$',
        views.songs_make_pptx,
        name='songs-pptx'),
    url(r'^(?P<song_id>\d+)/xml/$',
        views.songs_make_xml,
        name='songs-xml'),
]

templates/about.html
{% extends 'base_workspace.html' %}
{% load staticfiles %}

        {% block workspace %}
            <div class="row">
                <div class="col-sm-12">
                    <h3>
                        {{ website_info.title }}
                        <small><i>{{ website_info.version }}</i></small>
                    </h3>
                </div>
            </div>

            <div class="row about-page">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <h4>
                        Autor: Ralf Funk
                    </h4>
                    <p class="text-justify">
                        Este sistema (o también sitio web) fue desarrollado en el lenguage de programación
                        <a class="btn btn-default" role="button" target="_blank"
                           href="https://www.python.org/" title="https://www.python.org/">
                            <img class="img-responsive" src="{% static 'images/logo-python.png' %}"
                                 alt="logo-python">
                        </a>
                        , utilizando los frameworks
                        <a class="btn btn-default" role="button" target="_blank"
                           href="https://www.djangoproject.com/" title="https://www.djangoproject.com/">
                            <img class="img-responsive" src="{% static 'images/logo-django.png' %}"
                                 alt="logo-django">
                        </a>
                        y
                        <a class="btn btn-default" role="button" target="_blank"
                           href="http://getbootstrap.com/" title="http://getbootstrap.com/">
                            <img class="img-responsive" src="{% static 'images/logo-bootstrap.png' %}"
                                 alt="logo-bootstrap">
                        </a>
                        .
                    </p>
                    <p class="text-justify">
                        El código fuente de este sistema está publicado bajo la licencia
                        <a href="http://mozilla.org/MPL/2.0/" title="http://mozilla.org/MPL/2.0/"
                           target="_blank">
                            Mozilla Public License versión 2.0
                        </a>
                        y puedes encontrarlo en nuestro repositorio público de
                        <a class="btn btn-default" role="button" target="_blank"
                           href="https://bitbucket.org/ralffunk/mbg_websites_public"
                           title="https://bitbucket.org/ralffunk/mbg_websites_public">
                            <img class="img-responsive" src="{% static 'images/logo-bitbucket.png' %}"
                                 alt="logo-bitbucket">
                        </a>
                        .
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <h4>
                        Iglesia Hermanos Menonitas Concordia
                    </h4>
                    <p>
                        Página web:
                        <a href="http://mbg-concordia.org.py/" target="_blank">
                            http://mbg-concordia.org.py/
                        </a>
                    </p>
                    <p>
                        Asunción, Paraguay
                    </p>
                </div>
            </div>
        {% endblock %}

templates/base_workspace.html
{% extends 'website_base.html' %}
{% load staticfiles %}

    {% block css %}
        <link rel="stylesheet" href="{% static 'css/workspace.css' %}">
    {% endblock %}

    {% block body_content %}
        <div class="container workspace">
            <div class="row">
                <div class="col-xs-12">
                {% if breadcrumb %}
                    <ol class="breadcrumb">
                    {% for b in breadcrumb %}
                        {% if b.1 %}
                        <li><a title="{{ b.0 }}" href="{{ b.1 }}">{{ b.0|truncatechars:20 }}</a></li>
                        {% else %}
                        <li class="active">{{ b.0 }}</li>
                        {% endif %}
                    {% endfor %}
                    </ol>
                {% endif %}
                {% if page_title %}
                    <h3 class="page-title">{{ page_title }}</h3>
                {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="messages">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert">
                                <span>&times;</span>
                            </button>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                    </div>
                </div>
            </div>

        {% block workspace %}
        {% endblock %}
        </div>
    {% endblock %}

templates/stub_navbar.html
<!-- navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="dropdown">
                        <a class="navbar-brand dropdown-toggle" data-toggle="dropdown" role="button"
                           href="#">
                            {{ website_info.title }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">
                                <span class="glyphicon glyphicon-calendar"></span>
                                Calendario
                            </li>
                            <li>
                                <a href="{% url 'planners:start-page' %}">
                                    Inicio
                                </a>
                            </li>
                    {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'planners:calendars-list' %}">
                                    Calendarios
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'planners:events-list-all' %}">
                                    Eventos
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'planners:events-editable' %}">
                                    Planificación de eventos
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'planners:user-responsibilities' %}">
                                    Mis responsabilidades
                                </a>
                            </li>
                    {% endif %}
                            <li class="divider" role="separator"></li>
                            <li class="dropdown-header">
                                <span class="glyphicon glyphicon-music"></span>
                                Gestor de canciones
                            </li>
                            <li>
                                <a href="{% url 'songs:songs-list' %}">
                                    Canciones
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'songs:authors-list' %}">
                                    Autores
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'songs:songbooks-list' %}">
                                    Himnarios
                                </a>
                            </li>
                        {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'songs:styles-list' %}">
                                    Estilos de presentación
                                </a>
                            </li>
                        {% endif %}
                {% if user.is_authenticated %}
                    {% if perms.people.list_people %}
                            <li class="divider" role="separator"></li>
                            <li class="dropdown-header">
                                <span class="glyphicon glyphicon-user"></span>
                                Personas
                            </li>
                            <li>
                                <a href="{% url 'people:people-list' %}">
                                    Personas
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'people:birthday-list' %}">
                                    Lista de cumpleaños
                                </a>
                            </li>
                        {% if perms.people.list_marriages %}
                            <li>
                                <a href="{% url 'people:marriages-list' %}">
                                    Matrimonios
                                </a>
                            </li>
                        {% endif %}
                        {% if perms.people.list_groups %}
                            <li>
                                <a href="{% url 'people:groups-list' %}">
                                    Grupos
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    {% if perms.accounts.list_users or perms.auth.change_group %}
                            <li class="divider" role="separator"></li>
                            <li class="dropdown-header">
                                <span class="glyphicon glyphicon-cog"></span>
                                Administración
                            </li>
                            <li>
                                <a href="{% url 'accounts:users-list' %}">
                                    Usuarios
                                </a>
                            </li>
                        {% if perms.auth.change_group %}
                            <li>
                                <a href="{% url 'accounts:roles-list' %}">
                                    Roles
                                </a>
                            </li>
                        {% endif %}
                        {% if user.username == admin_username %}
                            <li>
                                <a href="{% url 'accounts:email-list' %}">
                                    Emails
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:session-list' %}">
                                    Sesiones
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:system-status' %}">
                                    Estado del sistema
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navbar">
                    <div class="navbar-right">
                        <p class="navbar-text">
                            {% now 'd-m-Y' %} &nbsp; {% now 'H:i' %}
                        </p>
                    {% if user.is_authenticated %}
                        <p class="navbar-text">
                            <a class="navbar-link" href="{% url 'accounts:profile' %}"
                               title="Ver mi perfil">
                                <span class="glyphicon glyphicon-user"></span>
                                {{ user.profile|truncatechars:20 }}
                            </a>
                        </p>
                        <p class="navbar-text">
                            <a class="navbar-link" href="{% url 'accounts:logout' %}" title="Cerrar sesión">
                                <span class="glyphicon glyphicon-off"></span>
                                <span class="visible-xs-inline">Cerrar sesión</span>
                            </a>
                        </p>
                    {% else %}
                        <p class="navbar-text">
                            <a class="navbar-link" title="Iniciar sesión" href="#m_loginModal"
                               data-toggle="modal">
                                Iniciar sesión
                            </a>
                        </p>
                    {% endif %}
                    </div>
                </div>
            </div>
        </nav>